(4-3)中級 パンくずリスト修正
yuta5190/ex-emp-management-bugfix pull request #12
Opened 2023-02-21 02:44 UTC by yuta5190

従業員一覧に戻るパンくずリストのリンクが切れているので修正
アンカー要素を追加した。

2023-02-21 04:39 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2023-02-21 04:39 UTC, igamasayuki commented on src/main/resources/templates/employee/detail.html
> +       <li class="active">
class="active"は不要なので削除してください。

2023-02-21 06:58 UTC, yuta5190 commented on src/main/resources/templates/employee/detail.html
> +       <li class="active">
消去しました。

2023-02-22 06:14 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2023-02-22 06:14 UTC, merged