初級 ダブルサブミット対策・ 従業員一覧の並び順
yuta5190/ex-emp-management-bugfix pull request #5
Opened 2023-02-17 08:34 UTC by yuta5190

ダブルサブミット対策のため、コントローラー８５行目にリダイレクト処理を入れました。

従業員一覧を並び替え表示するために、SQlを変更し入社日、名前順で行事されるように変更しました。

2023-02-17 08:45 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2023-02-17 08:45 UTC, igamasayuki commented on src/main/java/com/example/controller/AdministratorController.java
> +		return "redirect:administrator/login";
この書き方で動作しますか？
私の認識違いの場合は、口頭かSlackにてお知らせください。

2023-02-20 04:58 UTC, yuta5190 commented on src/main/java/com/example/controller/AdministratorController.java
> +		return "redirect:administrator/login";
動作していませんでしたので、リダイレクト先を変更いたしました。

2023-02-20 06:33 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2023-02-20 06:33 UTC, merged